services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service-bank
    ports:
      - '8761:8761'
    expose:
      - '8761'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
  config-service:
    build: ./config-service
    container_name: config-service-bank
    ports:
      - '9999:9999'
    expose:
      - '9999'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9999/actuator/health" ]
      interval: 10s
  customer-service-db:
    image: 'postgres:latest'
    container_name: customer-service-bank-db
    environment:
      - 'POSTGRES_DB=customer-db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5434:5432'
    expose:
      - '5434'
    volumes:
      - customer-db-data:/var/lib/postgresql/data
  customer-service:
    build: ./customer-service
    container_name: customer-service-bank
    ports:
      - '8084:8084'
    expose:
      - '8084'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8084/actuator/health" ]
      interval: 10s
  account-service-db:
    image: 'postgres:latest'
    container_name: account-service-bank-db
    environment:
      - 'POSTGRES_DB=account-db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5435:5432'
    expose:
      - '5435'
    volumes:
      - account-db-data:/var/lib/postgresql/data
  account-service:
    build: ./account-service
    container_name: account-service-bank
    ports:
      - '8085:8085'
    expose:
      - '8085'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      customer-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8085/actuator/health" ]
      interval: 10s
  gateway-service:
    build: ./gateway-service
    container_name: gateway-service-bank
    ports:
      - '8888:8888'
    expose:
      - '8888'
    environment:
      - DISCOVERY_SERVICE_URL=http://discovery-service:8761/eureka
      - CONFIG_SERVICE_URL=http://config-service:9999
    depends_on:
      config-service:
        condition: service_healthy
volumes:
  customer-db-data:
  account-db-data:
