
# for configuration complicated
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8084/
          predicates:
            - Path=/api/customers/**
        - id: account-service
          uri: http://localhost:8085/
          predicates:
            - Path=/api/accounts/**
server:
  port: 8888