services:
  postgres_customer:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=customer-db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5434:5432'
